# Generated by Django 4.2 on 2023-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_custommer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='img/custommer/'),
        ),
    ]
