# Generated by Django 4.2 on 2023-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_product_remove_custommer_image_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(null=True, to='order.product'),
        ),
    ]
